site_name: Python Tutorial
theme:
  name: material
  features:
    - navigation.sections
nav:
  - Overview: index.md
  - Basics: 
    - Syntax: basics/syntax.md
    - Variables and Data Types: basics/vars.md
    - Conditionals: basics/conditionals.md
    - Looping: basics/looping.md
    - Importing Modules: basics/importing.md
    - Functions: basics/functions.md
    - Exception Handling: basics/exceptions.md
  - Collections: 
    - Lists: collections/lists.md
    - Dictionaries: collections/dictionaries.md
#    - Tuples: collections/tuples.md
#    - Sets: collections/sets.md
#    - Comprehensions: collections/comprehensions.md
  - Object-Oriented Programming:
    - Classes and Objects: oop/classes.md
    - Inheritance: oop/inheritance.md
#  - Python Utilities:
#    - Map, Filter, Reduce: utils/functional.md
#    - Lambdas: utils/lambdas.md
  
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences