site_name: Python Tutorial
site_author: "Justin-Anthony Joco"

repo_name: justinjoco/python-tutorial
repo_url: https://github.com/justinjoco/python-tutorial

copyright:   'Copyright &copy; 2021 Justin-Anthony Joco'

theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.sections
    - navigation.tabs
nav:
  - Overview: index.md
  - Need to Know:
    - Basics: 
      - Syntax: basics/syntax.md
      - Variables and Data Types: basics/vars.md
      - Conditionals: basics/conditionals.md
      - Looping: basics/looping.md
      - Importing Modules: basics/importing.md
      - Functions: basics/functions.md
      - Exception Handling: basics/exceptions.md
    - Collections: 
      - Lists: collections/lists.md
      - Dictionaries: collections/dictionaries.md
    - Object-Oriented Programming:
      - Classes and Objects: oop/classes.md
      - Inheritance: oop/inheritance.md
  - Good to Know:
    - More on Collections:
      - Tuples: collections/tuples.md
      - Sets: collections/sets.md
      - Comprehensions: collections/comprehensions.md
    - Python Utilities:
      - Lambdas: utils/lambdas.md
      - Map, Filter, Reduce: utils/functional.md
  
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences